config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :drinks

end

app/models/drink.rb
class Drink < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	def how_old
		"I\'m " + self.age.to_s + " years old"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController






	def index
		#will have a view template
		@drinks = Drink.all.order("created_at DESC")
	end






	def show #display individual records - sort of a detailed view
		#will have a view template
		@drink = Drink.find(params[:id])
	end






	def new #display form for the new record
		#will have a view template
		@drink = Drink.new
	end






	def create #save new record
		#will not have a view template. It will save and redirect somewhere else
		@drink = Drink.new(allowed_params)
		if @drink.save
			redirect_to drinks_path
		else
			render "new"
		end
	end






	def edit #display form with existing records
		#will have a view template
		@drink = Drink.find(params[:id])
	end





	def update #save changes
		#will not have a view template. It will save and redirect somewhere else
		@drink = Drink.find(params[:id])
		if @drink.update_attributes(allowed_params)
			redirect_to drinks_path
		else
			render "new"
		end
	end






	def destroy
		#will not have a view template. It will delete and redirect somewhere else
		@drink = Drink.find(params[:id])
		@drink.destroy
		redirect_to drinks_path
	end






	private
	def allowed_params
		params.require(:drink).permit(:name, :size)
	end





end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all.order("created_at DESC")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drinks/edit.html.erb
<%= form_for @drink do |f| %>
	<%= f.label :name %><br>
	<%= f.text_field :name %><br>
	<%= f.label :size %><br>
	<%= f.text_field :size %><br>
	<%= f.submit "Save" %>
<% end %>

app/views/drinks/index.html.erb
<%= link_to "Add Drink", new_drink_path %>

<% @drinks.each do |d| %>
	<p>
		Name: <%= link_to d.name, drink_path(d) %><br>
		Size: <%= d.size %> | <%= link_to "Edit", edit_drink_path(d) %> | <%= link_to "Delete", d, method: :delete %>
	</p>
<% end %>

app/views/drinks/new.html.erb
<%= form_for @drink do |f| %>
	<%= f.label :name %><br>
	<%= f.text_field :name %><br>
	<%= f.label :size %><br>
	<%= f.text_field :size %><br>
	<%= f.submit "Save" %>
<% end %>

app/views/drinks/show.html.erb
<h1><%= @drink.name %></h1>

<%= link_to "Go Back", drinks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<% @users.each do |f| %>
	<p><%= f.name %></p>
	<p><%= f.how_old %></p>
	<p><%= f.bio %></p>
	<p>---</p>
<% end %>